apiVersion: v1
kind: Secret
metadata:
    name: postgres
data:
    POSTGRES_USER: ENC[AES256_GCM,data:qQ43rLmua/FOZ02PpZayXQ==,iv:ZCwbBdl6Hh9EqhasLaN5abb1jpRQMMWwxnftt3En0yk=,tag:vxRBW5hKFRPSMYYkyzV4hQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:2kJcr0blv1VDT5OqsqYUZjqT454=,iv:zPhT0edJgugMGWOMH2NftFgHEpwu2FW6/OlPcoPfqbg=,tag:zHUkyPyE2K+JI3ku+FZT0w==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:SF3hYcXMpGE=,iv:1cyOlUFh6Aw5J+tm/fVqd6HTUTj8RTW47Y62/mwRzJM=,tag:3lMmHrz78ReGQSGAlWcDaQ==,type:str]
immutable: true
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kdhxyxzul9q095wq9rc3hfkc4ukt2yze2474f46pk84wl5c7l4kqlxurfl
          enc: |
              -----BEGIN AGE ENCRYPTED FILE-----
              YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXZTEvL0FPUCs2RGJCSkxE
              Mys3YTY4T2xLNFdtU3lzeVZQQlhXNXlkS1Z3CkN2WVpOVDRVZkRGYnFOTmRCRis4
              VGJOeXkweHlSRXNPM1UzUUNodjFmTHcKLS0tIEVqelVuZklCN1ZKRHBlMFRFNitj
              Ym9HY3FFeXkrenJoelRFSS83QXFTMmcKcJRL+n5V3R1Wcze4ZROMni8PMzYv9O/e
              ja4ST/OzOfY6TLEHQFYv89fSunt4p3H8GVa1tBWH2xg74jKyL2X2XQ==
              -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-11-30T16:34:05Z"
    mac: ENC[AES256_GCM,data:vvC3CENMqGeFtHE/y6LntRZtu6IKQ6zXd1OsmowWszIDnJef3XHh28Wuk4gwPx055NHxPjDsfUzWVC6Y5g7wnx4b3z7thOj7vjG/gqS7M+S+SBPHWwr3K36GkWRYbLwlXO95ewfJWuhNWEEIUuq12PM8VbWVlsorUj8yEq8wEsM=,iv:5sUZkAzMQmyEGoZ1XhsEFzZCHx+GPjqwK1yAXMJKcHM=,tag:NZmfuNvFJGljzQx01xuiWQ==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.7.1
